name: Compile Rule-set

on:
  push:
    paths:
      - 'block.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sing-box
        run: |
          VERSION="1.8.0"
          wget https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/sing-box-${VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${VERSION}-linux-amd64.tar.gz
          mv sing-box-*/sing-box .

      - name: Compile JSON to SRS
        run: |
          chmod +x ./sing-box
          ./sing-box rule-set compile block.json || (echo "Compilation failed!" && exit 1)

      - name: Commit and Push SRS
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add block.srs
          # Проверяем, изменился ли файл, чтобы не было ошибки при коммите
          if git diff --cached --exit-code --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Compile rule-set"
            git push
          fi
